/* Biens factices — à remplacer par vos annonces réelles.
   Les chemins d'images correspondent aux prompts du fichier PROMPTS-IMAGES.md */
window.EDENEL_BIENS = [
  {
    id: "passy-haussmannien",
    titre: "Appartement haussmannien, étage noble",
    type: "Appartement",
    statut: "vente",
    ville: "Paris 16e — Passy",
    dept: "75",
    prix: 1890000,
    surface: 142,
    pieces: 5,
    chambres: 3,
    etage: "3e sur 6, ascenseur",
    dpe: "D",
    coupDeCoeur: true,
    description:
      "Au troisième étage d'un immeuble en pierre de taille de 1898, ce cinq-pièces traversant a conservé l'intégralité de ses éléments d'époque : parquet en point de Hongrie, cheminées en marbre, moulures et hauteur sous plafond de 3,20 m. La double réception ouvre sur trois balcons filants côté rue calme ; les trois chambres donnent sur cour arborée. Cave et service de gardiennage.",
    atouts: ["Double réception de 52 m²", "Trois balcons filants", "Cuisine séparée récemment refaite", "Cave et local à vélos", "Gardien à demeure"],
    images: ["bien-01-1.jpg", "bien-01-2.jpg", "bien-01-3.jpg", "bien-01-4.jpg", "bien-01-5.jpg", "bien-01-6.jpg", "bien-01-7.jpg"]
  },
  {
    id: "saint-germain-architecte",
    titre: "Maison d'architecte et jardin paysager",
    type: "Maison",
    statut: "vente",
    ville: "Saint-Germain-en-Laye",
    dept: "78",
    prix: 1450000,
    surface: 210,
    pieces: 7,
    chambres: 4,
    etage: "Sur 2 niveaux + sous-sol",
    dpe: "B",
    coupDeCoeur: false,
    description:
      "Construite en 2016 sur une parcelle de 820 m², cette maison contemporaine privilégie la lumière : baies vitrées toute hauteur au sud, pièce de vie de 65 m² ouverte sur une terrasse en ipé et un jardin planté sans vis-à-vis. Quatre chambres dont une suite parentale en rez-de-jardin, bureau indépendant, garage double. RER A à douze minutes à pied.",
    atouts: ["Pièce de vie de 65 m² plein sud", "Suite parentale de plain-pied", "Chauffage par pompe à chaleur", "Garage double + atelier", "Jardin de 820 m² sans vis-à-vis"],
    images: ["bien-02-1.jpg", "bien-02-2.jpg", "bien-02-3.jpg", "bien-02-4.jpg", "bien-02-5.jpg", "bien-02-6.jpg", "bien-02-7.jpg"]
  },
  {
    id: "montreuil-loft",
    titre: "Loft dans une ancienne fabrique",
    type: "Loft",
    statut: "vente",
    ville: "Montreuil — Croix de Chavaux",
    dept: "93",
    prix: 745000,
    surface: 118,
    pieces: 3,
    chambres: 2,
    etage: "Rez-de-chaussée sur cour privée",
    dpe: "C",
    coupDeCoeur: true,
    description:
      "Dans une ancienne fabrique de meubles réhabilitée en 2019, ce loft de 118 m² conjugue volumes industriels et prestations actuelles : verrières d'atelier, poutres métalliques, béton ciré, hauteur sous plafond de 4,5 m. Deux chambres en mezzanine, cuisine ouverte sur un salon de 55 m² et cour privative de 30 m². Métro à quatre minutes.",
    atouts: ["Hauteur sous plafond 4,5 m", "Cour privative de 30 m²", "Verrières d'atelier d'origine", "Copropriété de 8 lots", "Métro Croix de Chavaux à 4 min"],
    images: ["bien-03-1.jpg", "bien-03-2.jpg"]
  },
  {
    id: "neuilly-dernier-etage",
    titre: "Dernier étage avec vue sur le Bois",
    type: "Appartement",
    statut: "vente",
    ville: "Neuilly-sur-Seine — Sablons",
    dept: "92",
    prix: 1240000,
    surface: 96,
    pieces: 4,
    chambres: 2,
    etage: "7e et dernier, ascenseur",
    dpe: "C",
    coupDeCoeur: false,
    description:
      "Au dernier étage d'une résidence de standing des années 1970 entièrement ravalée, ce quatre-pièces profite d'une vue dégagée sur le bois de Boulogne et d'un balcon de 14 m² exposé ouest. Distribution parfaite : séjour de 34 m², cuisine équipée, deux chambres avec placards, salle de bains et salle d'eau. Parking en sous-sol et cave.",
    atouts: ["Vue dégagée sur le bois de Boulogne", "Balcon ouest de 14 m²", "Parking en sous-sol inclus", "Immeuble ravalé en 2023", "Métro Les Sablons à 3 min"],
    images: ["bien-04-1.jpg", "bien-04-2.jpg", "bien-04-3.jpg"]
  },
  {
    id: "versailles-maison-de-ville",
    titre: "Maison de ville, quartier Notre-Dame",
    type: "Maison",
    statut: "vente",
    ville: "Versailles — Notre-Dame",
    dept: "78",
    prix: 1320000,
    surface: 175,
    pieces: 6,
    chambres: 4,
    etage: "Sur 3 niveaux",
    dpe: "D",
    coupDeCoeur: false,
    description:
      "À deux pas du marché Notre-Dame, cette maison en meulière de 1905 a été restaurée dans le respect de son caractère : parquets d'origine, escalier en chêne, cheminées. Séjour double sur jardin clos de murs de 140 m², cuisine-salle à manger ouverte, quatre chambres et un bureau sous combles. Gare Rive-Droite à six minutes.",
    atouts: ["Meulière restaurée avec soin", "Jardin clos de murs de 140 m²", "Combles aménagés en bureau", "Cave voûtée", "Gare Versailles Rive-Droite à 6 min"],
    images: ["bien-05-1.jpg"]
  },
  {
    id: "paris-11-oberkampf",
    titre: "Trois-pièces lumineux sur cour arborée",
    type: "Appartement",
    statut: "vente",
    ville: "Paris 11e — Oberkampf",
    dept: "75",
    prix: 790000,
    surface: 68,
    pieces: 3,
    chambres: 2,
    etage: "4e sur 5, sans ascenseur",
    dpe: "E",
    coupDeCoeur: false,
    description:
      "Au calme absolu sur une cour plantée, ce trois-pièces d'angle bénéficie d'une triple exposition et d'une lumière continue. Séjour avec cuisine ouverte de 30 m², deux chambres, salle d'eau avec fenêtre. Immeuble ancien bien tenu, faibles charges. Idéal premier achat ou pied-à-terre.",
    atouts: ["Triple exposition", "Aucun vis-à-vis, sur cour plantée", "Faibles charges (110 €/mois)", "Cave", "Quartier vivant, métro Parmentier"],
    images: ["bien-06-1.jpg", "bien-06-2.jpg", "bien-06-3.jpg"]
  },
  {
    id: "vincennes-duplex-terrasse",
    titre: "Duplex avec terrasse plein ciel",
    type: "Appartement",
    statut: "vente",
    ville: "Vincennes — Centre",
    dept: "94",
    prix: 1095000,
    surface: 124,
    pieces: 5,
    chambres: 3,
    etage: "5e et 6e, ascenseur",
    dpe: "C",
    coupDeCoeur: true,
    description:
      "Aux deux derniers étages d'un immeuble récent, ce duplex offre une terrasse de 38 m² sans vis-à-vis face au château de Vincennes. Niveau bas : séjour de 45 m² ouvert sur la terrasse, cuisine équipée, chambre et salle d'eau. Niveau haut : deux chambres, salle de bains et bureau. Deux parkings et cave.",
    atouts: ["Terrasse de 38 m² sans vis-à-vis", "Vue sur le château", "Deux places de parking", "Immeuble de 2012, faibles charges", "RER A et métro à 5 min"],
    images: ["bien-07-1.jpg"]
  },
  {
    id: "boulogne-location-4p",
    titre: "Quatre-pièces familial, résidence arborée",
    type: "Appartement",
    statut: "location",
    ville: "Boulogne-Billancourt — Marcel Sembat",
    dept: "92",
    prix: 2650,
    surface: 82,
    pieces: 4,
    chambres: 3,
    etage: "2e sur 6, ascenseur",
    dpe: "C",
    coupDeCoeur: false,
    description:
      "Dans une résidence calme avec parc privé, ce quatre-pièces non meublé propose un séjour de 28 m² avec balcon, une cuisine équipée indépendante, trois chambres et une salle de bains. Parking en sous-sol. Disponible immédiatement. Loyer hors charges ; charges 210 €/mois (eau froide, chauffage collectif, entretien).",
    atouts: ["Non meublé, disponible immédiatement", "Balcon sur parc privé", "Parking en sous-sol", "Chauffage collectif", "Écoles et métro à moins de 5 min"],
    images: ["bien-08-1.jpg", "bien-08-2.jpg", "bien-08-3.jpg"]
  },
  {
    id: "paris-6-studio-meuble",
    titre: "Studio meublé, rue Jacob",
    type: "Studio",
    statut: "location",
    ville: "Paris 6e — Saint-Germain-des-Prés",
    dept: "75",
    prix: 1480,
    surface: 32,
    pieces: 1,
    chambres: 0,
    etage: "2e sur 4, sans ascenseur",
    dpe: "D",
    coupDeCoeur: false,
    description:
      "Dans un hôtel particulier du XVIIIe siècle, ce studio meublé avec goût conserve poutres apparentes et tomettes. Pièce principale de 24 m² avec couchage séparé par une bibliothèque, cuisine équipée, salle d'eau. Bail meublé d'un an. Loyer hors charges ; charges 90 €/mois.",
    atouts: ["Meublé avec soin, prêt à vivre", "Poutres et tomettes d'origine", "Immeuble du XVIIIe siècle", "Bail meublé 1 an", "Saint-Germain-des-Prés à 2 min"],
    images: ["bien-09-1.jpg", "bien-09-2.jpg"]
  },
  {
    id: "le-vesinet-maison-location",
    titre: "Maison familiale au cœur du Vésinet",
    type: "Maison",
    statut: "location",
    ville: "Le Vésinet — Centre",
    dept: "78",
    prix: 4900,
    surface: 190,
    pieces: 7,
    chambres: 5,
    etage: "Sur 2 niveaux",
    dpe: "D",
    coupDeCoeur: false,
    description:
      "Villa de 1925 rénovée sur un terrain paysager de 1 100 m² dans le quartier des lacs. Réception de 50 m² ouverte sur une véranda et le jardin, cuisine dînatoire, cinq chambres, deux salles de bains, garage. Non meublée, disponible au 1er octobre. Loyer hors charges.",
    atouts: ["Terrain paysager de 1 100 m²", "Véranda sur jardin", "Cinq chambres", "Garage et abri de jardin", "RER A Le Vésinet-Centre à 8 min"],
    images: ["bien-10-1.jpg", "bien-10-2.jpg", "bien-10-3.jpg"]
  }
];
